clip_init:
  clip_pretrain_path: c:\Users\q\Downloads\Aggregate_Lung_Segmentation\back_end\WeClip\clip_model\ViT-B-16.pt
  embedding_dim: 256
  in_channels:
  - 768
  - 768
  - 768
  - 768
dataset:
  crop_size: 320
  ignore_index: 255
  name_list_dir: c:\Users\q\Downloads\Aggregate_Lung_Segmentation\back_end\WeClip\datasets\voc
  num_classes: 21
  rescale_range:
  - 0.5
  - 2.0
  resize_range:
  - 512
  - 2048
  root_dir: c:\Users\q\Downloads\Aggregate_Lung_Segmentation\back_end\WeClip\voc_data
optimizer:
  betas:
  - 0.9
  - 0.999
  learning_rate: 2e-4
  type: AdamW
  weight_decay: 0.01
scheduler:
  power: 1.0
  warmup_iter: 50
  warmup_ratio: 1e-6
train:
  cam_iters: 10000
  eval_iters: 10000
  log_iters: 10000
  max_iters: 1000
  samples_per_gpu: 2
  split: train_aug
val:
  split: train
work_dir:
  ckpt_dir: checkpoints
  dir: work_dir_voc
  pred_dir: predictions
  segs_dir: segs
  tb_logger_dir: tb_logger
